dist: trusty
sudo: required

install:
  - wget -c https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git add -f --ignore-errors --all
    git -c user.name='travis' -c user.email='travis' commit -m update-website
    git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG master
  fi
