baseURL = "https://youngklsingers.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
publishDir = "docs"
# googleAnalytics = "UA-112176987-1"
[taxonomies]
  tag = "tags"


[params]
  title = "The Young KL Singers"
  subtitle    = "The Young KL Singers"

  cover       = "https://res.cloudinary.com/young-kl-singers/image/upload/c_scale,w_1600/v1520513268/YKLS_logo_Black_BG.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = "https://res.cloudinary.com/young-kl-singers/image/upload/c_scale,w_1600/v1520513268/YKLS_logo_Black_BG.jpg"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Th Young KL Singers"

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
